version: "3"
services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - ./volumes/dynamodb:/data
    ports:
      - "8000:8000"
    dynamodb-admin:
      container_name: test_dynamodb-admin
      image: aaronshaf/dynamodb-admin:latest
      environment:
        - DYNAMO_ENDPOINT=dynamodb-local:8000
      ports:
        - "8001:8001"
      depends_on:
        - dynamodb-local